"""
Corrected Grozi-120 Product Mapping
Generated using OpenAI Vision (GPT-4o) to identify actual product names.
"""

PRODUCT_NAME_MAP = {
    "grozi_1": "ReNu MultiPlus Contact Lens Solution",
    "grozi_2": "Chex Mix Traditional",
    "grozi_3": "Gardetto's Original Recipe Snack Mix",
    "grozi_4": "Cheerios Oat Cereal",
    "grozi_5": "Wrigley's Extra Gum",
    "grozi_6": "Wrigley's Doublemint Chewing Gum",
    "grozi_7": "Big Red Cinnamon Gum",
    "grozi_8": "Vicks DayQuil LiquiCaps",
    "grozi_9": "Cheez-It Baked Snack Crackers",
    "grozi_10": "Hershey's Milk Chocolate with Almonds",
    "grozi_11": "Twix Cookie Bars",
    "grozi_12": "Snickers Bar",
    "grozi_13": "Clorox Bleach",
    "grozi_14": "Clorox Ultra 2",
    "grozi_15": "Gatorade Lemon-Lime",
    "grozi_16": "Snyder's of Hanover Olde Tyme Pretzels",
    "grozi_17": "Unknown Product",
    "grozi_18": "Motrin IB Ibuprofen",
    "grozi_19": "Neosporin Antibiotic Ointment",
    "grozi_20": "Salsitas Tortilla Chips",
    "grozi_21": "Tic Tac Wintergreen Mints",
    "grozi_22": "Dentyne Ice Arctic Chill",
    "grozi_23": "Certs Peppermint Classic Mints",
    "grozi_24": "Bayer Aspirin",
    "grozi_25": "Nissin Cup Noodles Chicken Flavor",
    "grozi_26": "Windex Original Glass Cleaner",
    "grozi_27": "Morton Iodized Salt",
    "grozi_28": "Ziploc Sandwich Bags",
    "grozi_29": "Aleve Pain Reliever",
    "grozi_30": "Kit Kat King Size",
    "grozi_31": "Reese's Pieces",
    "grozi_32": "Kleenex Facial Tissue",
    "grozi_33": "ChapStick Lip Balm",
    "grozi_34": "Tide Laundry Detergent",
    "grozi_35": "Pringles Sour Cream & Onion",
    "grozi_36": "Pringles Potato Crisps",
    "grozi_37": "Starburst Candy",
    "grozi_38": "Skittles Original Fruit",
    "grozi_39": "Claritin Allergy Tablets",
    "grozi_40": "French's Yellow Mustard",
    "grozi_41": "Formula 409 Cleaner",
    "grozi_42": "Monster Energy",
    "grozi_43": "Mentos Mint Rolls",
    "grozi_44": "Tapatío Salsa Picante",
    "grozi_45": "Dove Deodorant",
    "grozi_46": "Band-Aid Flexible Fabric",
    "grozi_47": "Carmex Lip Balm",
    "grozi_48": "Rockstar Energy Drink",
    "grozi_49": "Vicks NyQuil Cough",
    "grozi_50": "Nestlé Crunch",
    "grozi_51": "Lay's Classic Potato Chips",
    "grozi_52": "Arm & Hammer Baking Soda",
    "grozi_53": "Martinelli's Apple Juice",
    "grozi_54": "Diet Coke with Lime",
    "grozi_55": "Sprite Soft Drink",
    "grozi_56": "Propel Fitness Water",
    "grozi_57": "Aviator Playing Cards",
    "grozi_58": "ACT II Butter Lovers Popcorn",
    "grozi_59": "Dr Pepper",
    "grozi_60": "Tylenol PM Extra Strength",
    "grozi_61": "Red Bull Sugarfree",
    "grozi_62": "Blistex Silk & Shine",
    "grozi_63": "Vicks NyQuil",
    "grozi_64": "Lindt Lindor Truffles",
    "grozi_65": "Lindt Excellence Dark Chocolate",
    "grozi_66": "Haribo Gold-Bears",
    "grozi_67": "Ritter Sport Weiße Voll-Nuss",
    "grozi_68": "Toblerone Chocolate",
    "grozi_69": "Manner Milk Chocolate Wafer",
    "grozi_70": "Pepperidge Farm Chocolate Chunk Cookies",
    "grozi_71": "Pepperidge Farm Milano",
    "grozi_72": "Tylenol Extra Strength",
    "grozi_73": "Starbucks Bottled Frappuccino",
    "grozi_74": "Yoo-hoo Chocolate Drink",
    "grozi_75": "Bull's-Eye Original Barbecue Sauce",
    "grozi_76": "Hershey's Symphony",
    "grozi_77": "Nabisco Nilla Wafers",
    "grozi_78": "Oberto Beef Jerky",
    "grozi_79": "David Sunflower Seeds Original",
    "grozi_80": "Hunt's Tomato Sauce",
    "grozi_81": "Kotex Lightdays Liners",
    "grozi_82": "Always Pads",
    "grozi_83": "Lipton Iced Tea",
    "grozi_84": "Soft Scrub with Bleach",
    "grozi_85": "Raid Flying Insect Killer",
    "grozi_86": "Shout Stain Remover",
    "grozi_87": "Gillette Foamy Regular",
    "grozi_88": "Campbell's Tomato Soup",
    "grozi_89": "Vivarin Caffeine Alertness Aid",
    "grozi_90": "Chef Boyardee Beef Ravioli",
    "grozi_91": "LifeStyles Ultra Sensitive",
    "grozi_92": "Crystal Geyser Alpine Spring Water",
    "grozi_93": "Luna Chocolate Pecan Pie",
    "grozi_94": "Kellogg's Raisin Bran",
    "grozi_95": "General Mills Honey Nut Cheerios",
    "grozi_96": "Unknown Product",
    "grozi_97": "Pepto-Bismol Chewables",
    "grozi_98": "Tabasco Sauce",
    "grozi_99": "Alka-Seltzer Plus Cold Medicine",
    "grozi_100": "Jack Link's The Original Extreme Snack Stick",
    "grozi_101": "Trojan Plus Lubricant",
    "grozi_102": "Trojan ENZ Lubricated Condoms",
    "grozi_103": "Colgate Extra Clean Toothbrush",
    "grozi_104": "Nabisco Wheat Thins Original",
    "grozi_105": "Mountain Dew",
    "grozi_106": "Haribo Frogs Gummi Candy",
    "grozi_107": "Nabisco Mini Chips Ahoy!",
    "grozi_108": "Jif Extra Crunchy Peanut Butter",
    "grozi_109": "Glade Powder Fresh Air Freshener Spray",
    "grozi_110": "Campbell's Cream of Chicken",
    "grozi_111": "Campbell's Chunky Classic Chicken Noodle",
    "grozi_112": "A.1. Steak Sauce",
    "grozi_113": "Rockstar Energy Drink",
    "grozi_114": "Kodak Elite Chrome 100 Film",
    "grozi_115": "Tostitos Scoops!",
    "grozi_116": "Ritter Sport Cappuccino",
    "grozi_117": "Ruffles Sour Cream & Onion Potato Chips",
    "grozi_118": "Ben & Jerry's Vanilla",
    "grozi_119": "Flavor Originals Vegetable Thins",
    "grozi_120": "Yoplait Original Strawberry Banana",
}

# For backwards compatibility
PRODUCT_PRICES = {name: 0.00 for name in PRODUCT_NAME_MAP}
PRODUCT_CATEGORIES = {name: "General" for name in PRODUCT_NAME_MAP}
